<a href="https://colab.research.google.com/github/AustinMoore032/Stat-class/blob/main/Austin_Moore_Lab_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Stats Notebook Lab #3

### Loops

In [2]:
for i in range(100): #i represents range 100 now, so when we print it will show 0-99
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [5]:
for i in range(5,8): #i range is 5-8 not including 8 and is printed
    print(i)

5
6
7


In [4]:
for i in range(3): #i in range 3 is 0-2
    print( "Test Number: " , i ) #Prints text infront of corresponding numbers.

Test Number:  0
Test Number:  1
Test Number:  2


### Functions

In [7]:
def square(x): #Defining square as x to the power of 2
    return x**2

In [8]:
square(5) #square 5 means 5*5

25

In [9]:
square(square(2)) #2 squared is 2*2 = 4 and 4 squared is 4*4 = 16

16

In [ ]:
square(square(square(2))) #2 squared is 2*2 = 4 and 4 squared is 4*4 = 16 and 16 squared is 16*16 = 256


256

In [10]:
square(123456) # it basically means the number times itself so 123456*123456

15241383936

In [11]:
square(square(5)) # 5*5 = 25 25*25= 625

625

In [13]:
def add_two(x): #defining add two statement to +2 to the number
    return x+2

In [ ]:
add_two(5) # 5+2

7

In [15]:
square(add_two(5)) #add two is first since it is inside so 5+2 = 7, 7 squared is 7*7 = 49

49

### Logical Branching

In [17]:
choice = "apple" #This is where we can have a variable selection and people could choose apple or something else, but for now we can just say people are choosing apple.

In [18]:
if choice == "apple": #If you choose apple it will print one text, and if you didn't type apples it will say the other for everything else.

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You choose apples.


In [21]:
choice = "orange" #defining new choice to orange

In [22]:
if choice == "apple": # now it will return not apples since our new choice is orange.

    print("You choose apples.")

else:
    
    print("You did not choose apples.")

You did not choose apples.


In [24]:
choice = "apple" #changing our choice back to apple

In [25]:
if choice == "apple": #Now if you choose apples or oranges you will get a different statement, and anything else will say you didn't choose apples or oranges.

    print("You choose apples.")
    print("Thank you, shop again!")
    print(2**123)

elif choice == "orange":

    print("You choose oranges.")
    print("Thank you, shop again!")

else:
    
    print("You did not choose apples or oranges.")
    print("Thank you, shop again!")

You choose apples.
Thank you, shop again!
10633823966279326983230456482242756608


### User Input

In [31]:
choice = input("Please enter your choice (i.e. apple): ") #input allows us to Enter choice i chose apple

Please enter your choice (i.e. apple): apple


In [32]:
choice #shows what we chose to put in the input box.

'apple'

In [33]:
if choice == "apple": # It returned i chose apples since i inputted apple above.

    print("You choose apples.")

elif choice == "oranges":

    print("You choose oranges.")

else:
    
    print("You did not choose apples or oranges.")

You choose apples.


#### Coins

In [34]:
import numpy as np # I changed numpy to np for easier reading of the code

In [35]:
np.random.random() # randomly gives us a number 0-1

0.6866358865413762

In [37]:
np.random.random() > 0.5 # returns true if the random number is greater than 0.5

False

In [38]:
def flip_coin(): # Now we define true and false as heads for true and tails for false.
    if np.random.random() > 0.5:
        print("Heads")
    else:
        print("Tails")

In [40]:
flip_coin() #now when we type flip coin it will flip either heads or tails all because of a 0-1 random number generator.

Heads


### Graphics Output

In [42]:
from IPython.core.display import display, HTML #Imports HTML

In [44]:
display(HTML('<h1>Hello, world!</h1>')) #Displays html contents

In [54]:
def coin(): #Defines coin as random number 0 or 1 since we have 2 after it it cant touch 2
  return np.random.randint(2)

In [52]:
coin()

0

In [55]:
display(HTML('<img src="https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg">')) #Display heads image

In [57]:
heads = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-front.jpg' #url linking picture to the word tails and heads
tails = 'https://random-ize.com/coin-flip/us-quarter/us-quarter-back.jpg'

In [60]:
def show_img(img): #Defining show img to open the picture as a img src
  display(HTML('<img src=' + img + '>'))

In [61]:
show_img(heads) #Displays heads url image

In [62]:
show_img(tails) #Displays tails url image

In [65]:
def flip_coin(): #defining flip coin to randomly pick a picture depending on 0-1

    if coin():
        show_img(heads)
    else:
        show_img(tails)

In [68]:
flip_coin() #flips heads or tails 0-1

In [69]:
for i in range(5): #flips 5 coins at once
    flip_coin()

In [ ]:
#@title Coin Flip

if coin():

  show_img(heads)

else:

  show_img(tails)

### Cards

In [73]:
def shuffle(x): #Defining shuffle to take a number and scatter the arrange
    for i in range(len(x)-1,0,-1):
        j = np.random.randint(0,i+1)
        x[i],x[j] = x[j],x[i]
        # print(j,x)
    return x

In [79]:
a = np.arange(52) #defining that it will scatter the 52 cards

In [80]:
shuffle(a) #randomly shuffles 52 cards 0-51

array([49, 32, 27,  5, 42, 51,  2, 21, 37, 12, 50, 23, 43, 39,  8,  9, 16,
       20,  1, 19, 48, 17, 13,  0, 25, 24, 22, 30, 36, 14,  4, 31, 10, 46,
       45, 28, 41,  7, 26, 40, 29,  6, 44, 11, 38,  3, 35, 15, 33, 34, 47,
       18])

In [81]:
np.random.permutation(52) #Shuffles cards randomly still? just more loops

array([16, 24, 15, 44, 12, 32, 29, 26,  5, 20,  6, 36, 38, 27, 30, 31,  0,
        2, 21,  3, 13, 19, 34, 23, 51, 25, 40, 18,  1,  4, 17, 37, 47, 45,
       41,  8, 43, 28,  9, 10, 14, 39, 46, 11, 49, 33, 42, 50, 22,  7, 35,
       48])

### Speed Test

In [84]:
%%timeit
shuffle(a) #performs in microseconds a little slower but shuffles

168 µs ± 2.1 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


In [83]:
%%timeit 
np.random.permutation(52) #performs in nanoseconds, meaning more loops shuffling

3.45 µs ± 209 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [85]:
import numpy as np #defines numpy as np

In [86]:
np.random.permutation(52) #gives us an array randomly numbered 0-51

array([21,  8, 33,  4,  0, 30,  2, 39, 16, 51, 44, 14, 27, 20, 17, 47, 13,
       43, 29, 48,  9, 10, 32, 41, 19,  6, 45, 25, 37, 11, 26,  5, 15, 18,
       38, 35,  1, 46, 23, 28, 36,  3,  7, 40, 49, 31, 22, 12, 34, 24, 42,
       50])

In [96]:
cards = np.random.permutation(52) #cards = 0-51

In [97]:
cards #displays the array

array([12,  3, 37, 20, 21, 29, 15, 42, 48, 43, 41, 23,  6,  0, 11,  7, 34,
       13, 36, 45, 38, 14, 30, 28, 49, 50,  1, 17, 25, 51, 44,  8, 27, 47,
       46, 40, 32, 18, 35, 22, 19,  2, 16,  5, 31,  9, 10, 33, 26, 24, 39,
        4])

In [102]:
cards[0] #Displays number with first card

12

In [104]:
cards[1] #displays number with second card

3

In [105]:
cards[2] #displays number with the 3rd card and so on.

37

<img src='http://www.milefoot.com/math/discrete/counting/images/cards.png'>

In [108]:
np.arange(52).reshape(4,13) #reshaped rows to 4 with 13 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38],
       [39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51]])

In [110]:
np.arange(52).reshape(4,13)%13 #reshaped making the cards go 0-12 in each row

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [111]:
np.arange(52).reshape(4,13)//13 #made rows the same number so we can define suits

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3]])

In [112]:
suits = ['Clubs','Spades','Hearts','Diamonds']
names = ['Ace','Two','Three','Four','Five','Six','Seven','Eight','Nine','Ten','Jack','Queen','King']

In [114]:
def card_name(card_number): #defining card name to show when we are given a card_number
    
    suit = card_number//13 #finds the suit
    name = card_number%13 #finds the name

    return names[name] + " of " + suits[suit] #adds of inbetween each suit -> name

In [117]:
card_name(0) #First cade is ace of clubs

'Ace of Clubs'

In [118]:
card_name(51) #last card is king of diamonds

'King of Diamonds'

In [128]:
cards = np.random.permutation(52) #Cards = random order now

In [129]:
top_of_deck         = card_name(cards[0]) # defining different card places in the deck
second_card_in_deck = card_name(cards[1])
last_card_in_deck   = card_name(cards[-1])

In [130]:
top_of_deck, second_card_in_deck, last_card_in_deck #everytime we run a new np random permutation for cards these will change accoring to the shuffle.

('Six of Clubs', 'King of Clubs', 'Eight of Spades')

In [ ]:
for i in range(5): #prints 5 cards names in a range list
    print(card_name(cards[i]))

Four of Spades
Six of Diamonds
Ace of Diamonds
Eight of Clubs
Three of Diamonds


In [ ]:
for i in range(15): #Prints 15 cards in a range list
    print(card_name(cards[i]))

Seven of Hearts
Ace of Clubs
King of Diamonds
Four of Hearts
Two of Hearts
Three of Spades
Ace of Diamonds
Seven of Diamonds
Four of Diamonds
King of Clubs
Five of Hearts
Three of Hearts
Six of Diamonds
Nine of Hearts
Eight of Hearts


https://www.improvemagic.com/all-playing-cards-names-with-pictures/

In [133]:
card_url_head = "https://www.improvemagic.com/wp-content/uploads/2020/11/" #cards picture urls
card_url_tail = ".png"

In [134]:
suit = ['k','p','s','l'] #suit and card letters instead of words
card = ['a','2','3','4','5','6','7','8','9','10','j','q','k']

In [145]:
i = np.random.randint(4) #shuffles for new integers
j = np.random.randint(13)

In [146]:
i,j #then we press this to display the new shuffle what row / column

(2, 5)

In [147]:
suit[i] #tells us the suit of i

's'

In [ ]:
card[j] # tells us the card of j

'q'

In [151]:
from IPython.core.display import display, HTML #imports HTML

In [150]:
def show_img(img): #show img now displays the HTML and img src
  display(HTML('<img src=' + img + '>'))

In [149]:
img = card_url_head + suit[i] + card[j] + card_url_tail #defining show img to show the card

In [153]:
show_img(img) #shows our current card

In [154]:
def card_image(card_number): #defines card image
    
    i = card_number//13 #finds the suit
    j = card_number%13 #finds the name

    return suit[i]+card[j] #displays letter(suit) of card followed by letter(number/name)

In [155]:
card_image(3) #displays suit then card

'k4'

In [156]:
img = card_url_head + card_image(3) + card_url_tail #defines img as card_image above to show the card

In [157]:
show_img(img) #shows card

In [158]:
for i in range(52): #shows all cards in range 0-51 by suit lowest to highest
    img = card_url_head + card_image(i) + card_url_tail
    show_img(img)